#!/usr/bin/env python3
"""Regenerate the '🆕 Recently added' block in both READMEs from git history (last 7 days).

Idempotent: rewrites only the text between <!-- RECENT-ADDED:START --> / <!-- RECENT-ADDED:END -->.
Usage: python3 .scripts/dsh_recent_added.py [--days 7] [--limit 12]
"""
import argparse, pathlib, re, subprocess

REPO = pathlib.Path(__file__).resolve().parent.parent
START, END = "<!-- RECENT-ADDED:START -->", "<!-- RECENT-ADDED:END -->"
ENTRY = re.compile(r"^\+\s*-\s*\[[^\]]+\]\(https?://[^\s)]+\)")


def recent(days, limit):
    """Added README entry lines in the last N days (newest commits first)."""
    r = subprocess.run(["git", "log", f"--since={days} days ago", "--pretty=format:@@%H%x09%ad",
                        "--date=short", "-p", "--unified=0", "--", "README.md"],
                       cwd=REPO, text=True, capture_output=True)
    out, seen, commit = [], set(), None
    for line in r.stdout.splitlines():
        if line.startswith("@@"):
            commit = line[2:]
        elif ENTRY.match(line):
            entry = line[1:].strip()
            key = entry.split("](")[0]
            if key not in seen:
                seen.add(key)
                out.append((commit, entry))
    return out[:limit], len(out)


def rewrite(path, items, total, days):
    t = path.read_text(encoding="utf-8")
    if START not in t or END not in t:
        print(f"{path.name}: markers missing, skip"); return
    if "Recently added" in t:
        title, note = "🆕 Recently added (last %d days)" % days, "_auto-generated by `.scripts/dsh_recent_added.py`_"
    else:
        title, note = "🆕 最近新增（近 %d 天）" % days, "_由 `.scripts/dsh_recent_added.py` 自动生成_"
    body = "\n".join(i[1] for i in items)
    more = "" if total <= len(items) else f"\n\n_…and {total - len(items)} more this week._"
    block = f"{START}\n<details>\n<summary>{title}</summary>\n\n{note}\n\n{body}{more}\n\n</details>\n{END}"
    t = re.sub(re.escape(START) + r".*?" + re.escape(END), block, t, flags=re.S)
    path.write_text(t, encoding="utf-8")
    print(f"{path.name}: wrote {len(items)}/{total} entries")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--days", type=int, default=7)
    ap.add_argument("--limit", type=int, default=12)
    a = ap.parse_args()
    items, total = recent(a.days, a.limit)
    for f in ("README.md", "README.zh-CN.md"):
        rewrite(REPO / f, items, total, a.days)
